(specifications->manifest (list
                            ;; base packages
                            "bash"
                            "bash-completion"
                            "glibc-locales"
                            "nss-certs"
                            ;; Common command line tools lest the container is too empty.
                            "coreutils"
                            "curl"
                            "grep"
                            "sed"
                            "wget"
                            "which"
                            ;; Toolchain and common libraries for "install.packages"
                            "cairo"
                            "cmake"
                            "curl"
                            "gawk"
                            "gcc-toolchain@10"
                            "gfortran-toolchain"
                            "gzip"
                            "libxt"
                            "make"
                            "openssl"
                            "pkg-config"
                            "tar"
                            "tcl"
                            "tzdata"
                            "unzip"
                            "zlib"
                            ;; common dependencies for r
                            "fontconfig"
                            "freetype"
                            "fribidi"
                            "harfbuzz"
                            "libjpeg"
                            "libpng"
                            "libtiff"
                            "libxml2"
                            "libwebp"
                            ;; r stuff
                            "r"
                            "rstudio"
                            "rstudio-server"
                            "r-xml2"
                          ))
