(specifications->manifest (list
                            ;; base packages
                            ;;"bash-minimal"
                            "bash"
                            "bash-completion"
                            "glibc-locales"
                            "nss-certs"
                            ;; Common command line tools lest the container is too empty.
                            "coreutils"
                            "curl"
                            "grep"
                            "sed"
                            "wget"
                            "which"
                            ;; Toolchain and common libraries for "install.packages"
                            "cairo"
                            "cmake"
                            "gcc-toolchain@10"
                            "gfortran-toolchain"
                            "gawk"
                            "gzip"
                            "libxt"
                            "make"
                            "openssl"
                            "pkg-config"
                            "r"
                            "rstudio"
                            "rstudio-server"
                            "tar"
                            "tcl"
                            "unzip"
                            "zlib"
                            ;; GIS/Geospatial crap
                            "gdal"
                            "libspatialite"
                            "proj"
                            ;; common dependencies for r
                            "fontconfig"
                            "fribidi"
                            "harfbuzz"
                            "libxml2"
                            ;; r stuff
                            "r"
                            "r-bayesplot"
                            "r-catools"
                            "r-caret"
                            "r-codetools"
                            "r-data-table"
                            "r-dplyr"
                            "r-devtools"
                            "r-httr"
                            ;;"r-jagstools"
                            "r-jagsui"
                            "r-jpeg"
                            "r-jsonlite"
                            "r-lubridate"
                            "r-missinghe"
                            "r-posterior"
                            "r-predproj"
                            "r-r2jags"
                            "r-rjags"
                            "r-rngtools"
                            "r-soildb"
                            "r-tidyverse"
                            "r-units"
                            "r-xml2"
                            "r-zoo"
                          ))
