(specifications->manifest (list
                            ;; base packages
                            "bash-minimal"
                            "glibc-locales"
                            "nss-certs"
                            ;; Common command line tools lest the container is too empty.
                            "coreutils"
                            "grep"
                            "which"
                            "wget"
                            "sed"
                            ;; Toolchain and common libraries for "install.packages"
                            "gcc-toolchain@10"
                            "gfortran-toolchain"
                            "gawk"
                            "tar"
                            "gzip"
                            "unzip"
                            "make"
                            "cmake"
                            "pkg-config"
                            "cairo"
                            "libxt"
                            "openssl"
                            "curl"
                            "zlib"
                            ;; gdal
                            "gdal"
                            ;; r stuff
                            "r"
                            "r-tidyverse"
                            "r-mgcv"
                            "r-plotly"
                            "r-patchwork"
                            "r-lubridate"
                            "r-iranges"
                            "r-data-table"
                            "r-brms"
                            "r-tidybayes"
                            "r-broom"
                          ))
