rm -rf Arabidopsis_simulated.plastome/
rm -rf EG30_R1/
rm -rf HSP90_mafft.fas
rm -rf HSP90_trimal.fas
rm -rf RAxML_bestTree.T6
rm -rf RAxML_info.T6
rm -rf RAxML_log.T6.RUN.0
rm -rf RAxML_log.T6.RUN.1
rm -rf RAxML_log.T6.RUN.10
rm -rf RAxML_log.T6.RUN.11
rm -rf RAxML_log.T6.RUN.12
rm -rf RAxML_log.T6.RUN.13
rm -rf RAxML_log.T6.RUN.14
rm -rf RAxML_log.T6.RUN.15
rm -rf RAxML_log.T6.RUN.16
rm -rf RAxML_log.T6.RUN.17
rm -rf RAxML_log.T6.RUN.18
rm -rf RAxML_log.T6.RUN.19
rm -rf RAxML_log.T6.RUN.2
rm -rf RAxML_log.T6.RUN.3
rm -rf RAxML_log.T6.RUN.4
rm -rf RAxML_log.T6.RUN.5
rm -rf RAxML_log.T6.RUN.6
rm -rf RAxML_log.T6.RUN.7
rm -rf RAxML_log.T6.RUN.8
rm -rf RAxML_log.T6.RUN.9
rm -rf RAxML_parsimonyTree.T6.RUN.0
rm -rf RAxML_parsimonyTree.T6.RUN.1
rm -rf RAxML_parsimonyTree.T6.RUN.10
rm -rf RAxML_parsimonyTree.T6.RUN.11
rm -rf RAxML_parsimonyTree.T6.RUN.12
rm -rf RAxML_parsimonyTree.T6.RUN.13
rm -rf RAxML_parsimonyTree.T6.RUN.14
rm -rf RAxML_parsimonyTree.T6.RUN.15
rm -rf RAxML_parsimonyTree.T6.RUN.16
rm -rf RAxML_parsimonyTree.T6.RUN.17
rm -rf RAxML_parsimonyTree.T6.RUN.18
rm -rf RAxML_parsimonyTree.T6.RUN.19
rm -rf RAxML_parsimonyTree.T6.RUN.2
rm -rf RAxML_parsimonyTree.T6.RUN.3
rm -rf RAxML_parsimonyTree.T6.RUN.4
rm -rf RAxML_parsimonyTree.T6.RUN.5
rm -rf RAxML_parsimonyTree.T6.RUN.6
rm -rf RAxML_parsimonyTree.T6.RUN.7
rm -rf RAxML_parsimonyTree.T6.RUN.8
rm -rf RAxML_parsimonyTree.T6.RUN.9
rm -rf RAxML_result.T6.RUN.0
rm -rf RAxML_result.T6.RUN.1
rm -rf RAxML_result.T6.RUN.10
rm -rf RAxML_result.T6.RUN.11
rm -rf RAxML_result.T6.RUN.12
rm -rf RAxML_result.T6.RUN.13
rm -rf RAxML_result.T6.RUN.14
rm -rf RAxML_result.T6.RUN.15
rm -rf RAxML_result.T6.RUN.16
rm -rf RAxML_result.T6.RUN.17
rm -rf RAxML_result.T6.RUN.18
rm -rf RAxML_result.T6.RUN.19
rm -rf RAxML_result.T6.RUN.2
rm -rf RAxML_result.T6.RUN.3
rm -rf RAxML_result.T6.RUN.4
rm -rf RAxML_result.T6.RUN.5
rm -rf RAxML_result.T6.RUN.6
rm -rf RAxML_result.T6.RUN.7
rm -rf RAxML_result.T6.RUN.8
rm -rf RAxML_result.T6.RUN.9
rm -rf SeedUsed
rm -rf test.out
rm -rf test_files/HSP90.fas.amb
rm -rf test_files/HSP90.fas.ann
rm -rf test_files/HSP90.fas.bwt
rm -rf test_files/HSP90.fas.pac
rm -rf test_files/HSP90.fas.sa
rm -rf test_files/example.phy.bionj
rm -rf test_files/example.phy.ckp.gz
rm -rf test_files/example.phy.iqtree
rm -rf test_files/example.phy.log
rm -rf test_files/example.phy.mldist
rm -rf test_files/example.phy.model.gz
rm -rf test_files/example.phy.treefile
rm -rf test_files/mcmc.txt
rm -rf test_files/mcmc.txt.tmp
rm -rf test_files/mm10_treeshrink/
rm -rf test_files/out.txt
