#!/bin/bash

# Astral needs run not exec, that's why it has its own script
ln -s astral.sh astral
ln -s bioinformatics.sh beast
ln -s bioinformatics.sh mafft
ln -s bioinformatics.sh trimal
ln -s bioinformatics.sh bmge
ln -s bioinformatics.sh bpp
ln -s bioinformatics.sh bwa
ln -s bioinformatics.sh exonerate
ln -s bioinformatics.sh FastTree
ln -s bioinformatics.sh get_organelle_from_reads.py
ln -s bioinformatics.sh reads_first.py
ln -s bioinformatics.sh ibpp
ln -s bioinformatics.sh iqtree
ln -s bioinformatics.sh pal2nal.pl
ln -s bioinformatics.sh raxmlHPC
ln -s bioinformatics.sh samtools
ln -s bioinformatics.sh run_treeshrink.py
ln -s bioinformatics.sh bcftools
ln -s bioinformatics.sh plot-vcfstats
ln -s bioinformatics.sh Xcalcmem.sh
ln -s bioinformatics.sh a_sample_mt.sh
ln -s bioinformatics.sh addadapters.sh
ln -s bioinformatics.sh addssu.sh
ln -s bioinformatics.sh adjusthomopolymers.sh
ln -s bioinformatics.sh alltoall.sh
ln -s bioinformatics.sh analyzeaccession.sh
ln -s bioinformatics.sh analyzegenes.sh
ln -s bioinformatics.sh analyzesketchresults.sh
ln -s bioinformatics.sh applyvariants.sh
ln -s bioinformatics.sh bbcms.sh
ln -s bioinformatics.sh bbcountunique.sh
ln -s bioinformatics.sh bbduk.sh
ln -s bioinformatics.sh bbest.sh
ln -s bioinformatics.sh bbfakereads.sh
ln -s bioinformatics.sh bbmap.sh
ln -s bioinformatics.sh bbmapskimmer.sh
ln -s bioinformatics.sh bbmask.sh
ln -s bioinformatics.sh bbmerge-auto.sh
ln -s bioinformatics.sh bbmerge.sh
ln -s bioinformatics.sh bbnorm.sh
ln -s bioinformatics.sh bbrealign.sh
ln -s bioinformatics.sh bbrename.sh
ln -s bioinformatics.sh bbsketch.sh
ln -s bioinformatics.sh bbsplit.sh
ln -s bioinformatics.sh bbsplitpairs.sh
ln -s bioinformatics.sh bbstats.sh
ln -s bioinformatics.sh bbversion.sh
ln -s bioinformatics.sh bbwrap.sh
ln -s bioinformatics.sh bloomfilter.sh
ln -s bioinformatics.sh bloomfilterparser.sh
ln -s bioinformatics.sh calcmem.sh
ln -s bioinformatics.sh calctruequality.sh
ln -s bioinformatics.sh callgenes.sh
ln -s bioinformatics.sh callpeaks.sh
ln -s bioinformatics.sh callvariants.sh
ln -s bioinformatics.sh callvariants2.sh
ln -s bioinformatics.sh clumpify.sh
ln -s bioinformatics.sh commonkmers.sh
ln -s bioinformatics.sh comparegff.sh
ln -s bioinformatics.sh comparesketch.sh
ln -s bioinformatics.sh comparessu.sh
ln -s bioinformatics.sh comparevcf.sh
ln -s bioinformatics.sh consect.sh
ln -s bioinformatics.sh consensus.sh
ln -s bioinformatics.sh countbarcodes.sh
ln -s bioinformatics.sh countgc.sh
ln -s bioinformatics.sh countsharedlines.sh
ln -s bioinformatics.sh crossblock.sh
ln -s bioinformatics.sh crosscontaminate.sh
ln -s bioinformatics.sh cutgff.sh
ln -s bioinformatics.sh cutprimers.sh
ln -s bioinformatics.sh decontaminate.sh
ln -s bioinformatics.sh dedupe.sh
ln -s bioinformatics.sh dedupe2.sh
ln -s bioinformatics.sh dedupebymapping.sh
ln -s bioinformatics.sh demuxbyname.sh
ln -s bioinformatics.sh diskbench.sh
ln -s bioinformatics.sh estherfilter.sh
ln -s bioinformatics.sh explodetree.sh
ln -s bioinformatics.sh fetchproks.sh
ln -s bioinformatics.sh filterassemblysummary.sh
ln -s bioinformatics.sh filterbarcodes.sh
ln -s bioinformatics.sh filterbycoverage.sh
ln -s bioinformatics.sh filterbyname.sh
ln -s bioinformatics.sh filterbysequence.sh
ln -s bioinformatics.sh filterbytaxa.sh
ln -s bioinformatics.sh filterbytile.sh
ln -s bioinformatics.sh filterlines.sh
ln -s bioinformatics.sh filterqc.sh
ln -s bioinformatics.sh filtersam.sh
ln -s bioinformatics.sh filtersilva.sh
ln -s bioinformatics.sh filtersubs.sh
ln -s bioinformatics.sh filtervcf.sh
ln -s bioinformatics.sh fixgaps.sh
ln -s bioinformatics.sh fungalrelease.sh
ln -s bioinformatics.sh fuse.sh
ln -s bioinformatics.sh gbff2gff.sh
ln -s bioinformatics.sh getreads.sh
ln -s bioinformatics.sh gi2ancestors.sh
ln -s bioinformatics.sh gi2taxid.sh
ln -s bioinformatics.sh gitable.sh
ln -s bioinformatics.sh grademerge.sh
ln -s bioinformatics.sh gradesam.sh
ln -s bioinformatics.sh icecreamfinder.sh
ln -s bioinformatics.sh icecreamgrader.sh
ln -s bioinformatics.sh icecreammaker.sh
ln -s bioinformatics.sh idmatrix.sh
ln -s bioinformatics.sh idtree.sh
ln -s bioinformatics.sh invertkey.sh
ln -s bioinformatics.sh kapastats.sh
ln -s bioinformatics.sh kcompress.sh
ln -s bioinformatics.sh keepbestcopy.sh
ln -s bioinformatics.sh khist.sh
ln -s bioinformatics.sh kmercountexact.sh
ln -s bioinformatics.sh kmercountmulti.sh
ln -s bioinformatics.sh kmercoverage.sh
ln -s bioinformatics.sh kmerfilterset.sh
ln -s bioinformatics.sh kmerlimit.sh
ln -s bioinformatics.sh kmerlimit2.sh
ln -s bioinformatics.sh kmerposition.sh
ln -s bioinformatics.sh kmutate.sh
ln -s bioinformatics.sh license.txt
ln -s bioinformatics.sh lilypad.sh
ln -s bioinformatics.sh loadreads.sh
ln -s bioinformatics.sh loglog.sh
ln -s bioinformatics.sh makechimeras.sh
ln -s bioinformatics.sh makecontaminatedgenomes.sh
ln -s bioinformatics.sh makepolymers.sh
ln -s bioinformatics.sh mapPacBio.sh
ln -s bioinformatics.sh matrixtocolumns.sh
ln -s bioinformatics.sh mergeOTUs.sh
ln -s bioinformatics.sh mergebarcodes.sh
ln -s bioinformatics.sh mergepgm.sh
ln -s bioinformatics.sh mergeribo.sh
ln -s bioinformatics.sh mergesam.sh
ln -s bioinformatics.sh mergesketch.sh
ln -s bioinformatics.sh mergesorted.sh
ln -s bioinformatics.sh msa.sh
ln -s bioinformatics.sh mutate.sh
ln -s bioinformatics.sh muxbyname.sh
ln -s bioinformatics.sh partition.sh
ln -s bioinformatics.sh phylip2fasta.sh
ln -s bioinformatics.sh pileup.sh
ln -s bioinformatics.sh pipelines
ln -s bioinformatics.sh plotflowcell.sh
ln -s bioinformatics.sh plotgc.sh
ln -s bioinformatics.sh postfilter.sh
ln -s bioinformatics.sh printtime.sh
ln -s bioinformatics.sh processfrag.sh
ln -s bioinformatics.sh processhi-c.sh
ln -s bioinformatics.sh processspeed.sh
ln -s bioinformatics.sh randomgenome.sh
ln -s bioinformatics.sh randomreads.sh
ln -s bioinformatics.sh readlength.sh
ln -s bioinformatics.sh readqc.sh
ln -s bioinformatics.sh reducesilva.sh
ln -s bioinformatics.sh reformat.sh
ln -s bioinformatics.sh reformatpb.sh
ln -s bioinformatics.sh removebadbarcodes.sh
ln -s bioinformatics.sh removecatdogmousehuman.sh
ln -s bioinformatics.sh removehuman.sh
ln -s bioinformatics.sh removehuman2.sh
ln -s bioinformatics.sh removemicrobes.sh
ln -s bioinformatics.sh removesmartbell.sh
ln -s bioinformatics.sh rename.sh
ln -s bioinformatics.sh renameimg.sh
ln -s bioinformatics.sh repair.sh
ln -s bioinformatics.sh replaceheaders.sh
ln -s bioinformatics.sh representative.sh
ln -s bioinformatics.sh rqcfilter.sh
ln -s bioinformatics.sh rqcfilter2.sh
ln -s bioinformatics.sh runhmm.sh
ln -s bioinformatics.sh samtoroc.sh
ln -s bioinformatics.sh seal.sh
ln -s bioinformatics.sh sendsketch.sh
ln -s bioinformatics.sh shred.sh
ln -s bioinformatics.sh shrinkaccession.sh
ln -s bioinformatics.sh shuffle.sh
ln -s bioinformatics.sh shuffle2.sh
ln -s bioinformatics.sh sketch.sh
ln -s bioinformatics.sh sketchblacklist.sh
ln -s bioinformatics.sh sketchblacklist2.sh
ln -s bioinformatics.sh sortbyname.sh
ln -s bioinformatics.sh splitbytaxa.sh
ln -s bioinformatics.sh splitnextera.sh
ln -s bioinformatics.sh splitribo.sh
ln -s bioinformatics.sh splitsam.sh
ln -s bioinformatics.sh splitsam4way.sh
ln -s bioinformatics.sh splitsam6way.sh
ln -s bioinformatics.sh stats.sh
ln -s bioinformatics.sh statswrapper.sh
ln -s bioinformatics.sh streamsam.sh
ln -s bioinformatics.sh subsketch.sh
ln -s bioinformatics.sh summarizecontam.sh
ln -s bioinformatics.sh summarizecoverage.sh
ln -s bioinformatics.sh summarizecrossblock.sh
ln -s bioinformatics.sh summarizemerge.sh
ln -s bioinformatics.sh summarizequast.sh
ln -s bioinformatics.sh summarizescafstats.sh
ln -s bioinformatics.sh summarizeseal.sh
ln -s bioinformatics.sh summarizesketch.sh
ln -s bioinformatics.sh synthmda.sh
ln -s bioinformatics.sh tadpipe.sh
ln -s bioinformatics.sh tadpole.sh
ln -s bioinformatics.sh tadwrapper.sh
ln -s bioinformatics.sh taxonomy.sh
ln -s bioinformatics.sh taxserver.sh
ln -s bioinformatics.sh taxsize.sh
ln -s bioinformatics.sh taxtree.sh
ln -s bioinformatics.sh testfilesystem.sh
ln -s bioinformatics.sh testformat.sh
ln -s bioinformatics.sh testformat2.sh
ln -s bioinformatics.sh tetramerfreq.sh
ln -s bioinformatics.sh textfile.sh
ln -s bioinformatics.sh translate6frames.sh
ln -s bioinformatics.sh unicode2ascii.sh
ln -s bioinformatics.sh unzip.sh
ln -s bioinformatics.sh vcf2gff.sh
ln -s bioinformatics.sh webcheck.sh
